[workspace]
members = ["crates/*"]
default-members = ["crates/app"]

[workspace.package]
version = "0.4.0"
authors = ["Allypost"]
description = "A meme downloader"
edition = "2021"

[profile.release]
strip = true
# opt-level = "z"
# lto = true
# codegen-units = 1
