[package]
name = "app-helpers"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
base64 = "0.21.2"
app-config = { version = "*", path = "../app-config" }
log = "0.4.19"
serde = "1.0.164"
serde_json = "1.0.96"
trash = "3.0.3"
