[package]
name = "fixers"
version = "0.3.0"
edition = "2021"

[dependencies]
config = { version = "*", path = "../config" }
filetime = "0.2.21"
fs_extra = "1.3.0"
helpers = { version = "*", path = "../helpers" }
infer = "0.13.0"
log = "0.4.19"
rayon = "1.7.0"
